# Generated by Django 5.2.6 on 2025-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField()),
                ('employee_id', models.CharField(max_length=50)),
                ('vehicle_id', models.IntegerField()),
                ('trip_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('in_bus', models.IntegerField()),
                ('arrival_time', models.FloatField()),
                ('distance', models.FloatField()),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('shift_time', models.TimeField()),
                ('start', models.CharField(max_length=250)),
                ('end', models.CharField(max_length=250)),
                ('pickup_drop_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField()),
                ('trip_type', models.CharField(max_length=50)),
                ('transportation_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('acc_code', models.IntegerField()),
                ('acc_name', models.CharField(max_length=250)),
                ('store_code', models.IntegerField()),
                ('store_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('shift_time', models.TimeField()),
                ('staff', models.IntegerField()),
                ('acc_lattitude', models.FloatField()),
                ('acc_longitude', models.FloatField()),
                ('store_latitude', models.FloatField()),
                ('store_longitude', models.FloatField()),
            ],
        ),
    ]
