class SchemaSchedule:
    TRIP_TYPE = 'trip_type'
    TRANSPORTATION_TYPE = 'transportation_type'
    REGION = 'region'
    CITY = 'city'
    ACC_CODE = 'acc_code'
    ACC_NAME = 'acc_name'
    STORE_CODE = 'store_code'
    STORE_NAME = 'store_name'
    BRAND = 'brand'
    SHIFT_TIME = 'shift_time'
    STAFF = 'staff'
    ACC_LAT = 'acc_lattitude'
    ACC_LON = 'acc_longitude'
    STORE_LAT = 'store_latitude'
    STORE_LON = 'store_longitude'
    UPLOAD_TIME = 'upload_time'